# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - manual

pool:
  vmImage: ubuntu-20.04

jobs:
- job: Build
  steps:
  - task: Maven@3
    displayName: Build with Maven
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Dtest=FaresTest,SimpleTest'
      goals: 'package'
  
  - task: Maven@3
    inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'

  - task: CopyFiles@2
    displayName: Copy Artifacts
    inputs:
      Contents: '**'
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

- job: SonarQube
  dependsOn: Build
  steps:
  - task: SonarQubeScanner@2
    displayName: Run SonarQube Analysis
    inputs:
      SonarQube: 'cicdgen-sonar-svc-conn'
      projectKey: 'my-project'
      scannerMode: 'CLI'

- job: Deploy
  dependsOn: SonarQube
  steps:
  - task: Kubernetes@1
    displayName: Deploy to Kubernetes
    inputs:
      action: 'Deploy'
      namespace: 'default'
      kubernetesServiceConnection: 'CICDGen-Kube-SVC-Conn'
      manifests: '$(Build.ArtifactStagingDirectory)/deployment.yml'