trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'KubernetesCluster'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'cicdgen-sonar-svc-conn'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'new-cicdgen-project'
    cliProjectName: 'new-cicdgen-project'
    cliSources: 'src'
    extraProperties: |
      sonar.java.binaries=$(System.DefaultWorkingDirectory)/target
      sonar.java.libraries=$(System.DefaultWorkingDirectory)/target/lib

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
