# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - manual

pool:
  vmImage: ubuntu-20.04
steps:
  - task: Maven@3
    displayName: Build with Maven
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Dtest=FaresTest,SimpleTest'
      goals: 'package'
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'

  - task: CopyFiles@2
    displayName: Copy Artifacts
    inputs:
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
  - task: SonarQubePrepare@4
    displayName: Run SonarQube Analysis
    inputs:
      SonarQube: 'cicdgen-sonar-svc-conn'
      scannerMode: 'CLI'
      configMode: 'file'

  - task: KubernetesManifest@1
    displayName: Deploy to Kubernetes
    inputs:
      action: 'Deploy'
      namespace: 'default'
      kubernetesServiceConnection: 'CICDGen-Kube-SVC-Conn'
      manifests: '$(Build.ArtifactStagingDirectory)/deployment.yml'
