aws_region = "us-west-1"
cluster-name = "terraform-eks-demo"
access_key = "AKIAYODUIHLYMFW5BRCJ"
secret_key = "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"
demo-nodename = "terraform-eks-demo-node"
node_group_name = "demo"